package net.zylk.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.zylk.liferay.portal.model.Newsletter;
import net.zylk.liferay.portal.service.NewsletterLocalServiceUtil;

/**
 * The extended model base implementation for the Newsletter service. Represents a row in the &quot;ZN_Newsletter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsletterImpl}.
 * </p>
 *
 * @author zylk.net
 * @see NewsletterImpl
 * @see net.zylk.liferay.portal.model.Newsletter
 * @generated
 */
public abstract class NewsletterBaseImpl extends NewsletterModelImpl
    implements Newsletter {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a newsletter model instance should use the {@link Newsletter} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            NewsletterLocalServiceUtil.addNewsletter(this);
        } else {
            NewsletterLocalServiceUtil.updateNewsletter(this);
        }
    }
}
