package net.zylk.liferay.portal.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import net.zylk.liferay.portal.model.Subscriptor;
import net.zylk.liferay.portal.service.SubscriptorLocalServiceUtil;

/**
 * The extended model base implementation for the Subscriptor service. Represents a row in the &quot;ZN_Subscriptor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubscriptorImpl}.
 * </p>
 *
 * @author zylk.net
 * @see SubscriptorImpl
 * @see net.zylk.liferay.portal.model.Subscriptor
 * @generated
 */
public abstract class SubscriptorBaseImpl extends SubscriptorModelImpl
    implements Subscriptor {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this class directly. All methods that expect a subscriptor model instance should use the {@link Subscriptor} interface instead.
     */
    @Override
    public void persist() throws SystemException {
        if (this.isNew()) {
            SubscriptorLocalServiceUtil.addSubscriptor(this);
        } else {
            SubscriptorLocalServiceUtil.updateSubscriptor(this);
        }
    }
}
