package net.zylk.liferay.portal.model;

import com.liferay.portal.LocaleException;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Locale;
import java.util.Map;

/**
 * The base model interface for the Category service. Represents a row in the &quot;ZN_Category&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.zylk.liferay.portal.model.impl.CategoryModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.zylk.liferay.portal.model.impl.CategoryImpl}.
 * </p>
 *
 * @author zylk.net
 * @see Category
 * @see net.zylk.liferay.portal.model.impl.CategoryImpl
 * @see net.zylk.liferay.portal.model.impl.CategoryModelImpl
 * @generated
 */
public interface CategoryModel extends BaseModel<Category> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a category model instance should use the {@link Category} interface instead.
     */

    /**
     * Returns the primary key of this category.
     *
     * @return the primary key of this category
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this category.
     *
     * @param primaryKey the primary key of this category
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the category ID of this category.
     *
     * @return the category ID of this category
     */
    public long getCategoryId();

    /**
     * Sets the category ID of this category.
     *
     * @param categoryId the category ID of this category
     */
    public void setCategoryId(long categoryId);

    /**
     * Returns the company ID of this category.
     *
     * @return the company ID of this category
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this category.
     *
     * @param companyId the company ID of this category
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this category.
     *
     * @return the group ID of this category
     */
    public long getGroupId();

    /**
     * Sets the group ID of this category.
     *
     * @param groupId the group ID of this category
     */
    public void setGroupId(long groupId);

    /**
     * Returns the name of this category.
     *
     * @return the name of this category
     */
    public String getName();

    /**
     * Returns the localized name of this category in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param locale the locale of the language
     * @return the localized name of this category
     */
    @AutoEscape
    public String getName(Locale locale);

    /**
     * Returns the localized name of this category in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param locale the local of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this category. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
     */
    @AutoEscape
    public String getName(Locale locale, boolean useDefault);

    /**
     * Returns the localized name of this category in the language. Uses the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @return the localized name of this category
     */
    @AutoEscape
    public String getName(String languageId);

    /**
     * Returns the localized name of this category in the language, optionally using the default language if no localization exists for the requested language.
     *
     * @param languageId the ID of the language
     * @param useDefault whether to use the default language if no localization exists for the requested language
     * @return the localized name of this category
     */
    @AutoEscape
    public String getName(String languageId, boolean useDefault);

    @AutoEscape
    public String getNameCurrentLanguageId();

    @AutoEscape
    public String getNameCurrentValue();

    /**
     * Returns a map of the locales and localized names of this category.
     *
     * @return the locales and localized names of this category
     */
    public Map<Locale, String> getNameMap();

    /**
     * Sets the name of this category.
     *
     * @param name the name of this category
     */
    public void setName(String name);

    /**
     * Sets the localized name of this category in the language.
     *
     * @param name the localized name of this category
     * @param locale the locale of the language
     */
    public void setName(String name, Locale locale);

    /**
     * Sets the localized name of this category in the language, and sets the default locale.
     *
     * @param name the localized name of this category
     * @param locale the locale of the language
     * @param defaultLocale the default locale
     */
    public void setName(String name, Locale locale, Locale defaultLocale);

    public void setNameCurrentLanguageId(String languageId);

    /**
     * Sets the localized names of this category from the map of locales and localized names.
     *
     * @param nameMap the locales and localized names of this category
     */
    public void setNameMap(Map<Locale, String> nameMap);

    /**
     * Sets the localized names of this category from the map of locales and localized names, and sets the default locale.
     *
     * @param nameMap the locales and localized names of this category
     * @param defaultLocale the default locale
     */
    public void setNameMap(Map<Locale, String> nameMap, Locale defaultLocale);

    /**
     * Returns the description of this category.
     *
     * @return the description of this category
     */
    @AutoEscape
    public String getDescription();

    /**
     * Sets the description of this category.
     *
     * @param description the description of this category
     */
    public void setDescription(String description);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    public String[] getAvailableLanguageIds();

    public String getDefaultLanguageId();

    public void prepareLocalizedFieldsForImport() throws LocaleException;

    public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
        throws LocaleException;

    @Override
    public Object clone();

    @Override
    public int compareTo(Category category);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Category> toCacheModel();

    @Override
    public Category toEscapedModel();

    @Override
    public Category toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
