package net.zylk.liferay.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the MailingLang service. Represents a row in the &quot;ZN_MailingLang&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.zylk.liferay.portal.model.impl.MailingLangModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.zylk.liferay.portal.model.impl.MailingLangImpl}.
 * </p>
 *
 * @author zylk.net
 * @see MailingLang
 * @see net.zylk.liferay.portal.model.impl.MailingLangImpl
 * @see net.zylk.liferay.portal.model.impl.MailingLangModelImpl
 * @generated
 */
public interface MailingLangModel extends BaseModel<MailingLang> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a mailing lang model instance should use the {@link MailingLang} interface instead.
     */

    /**
     * Returns the primary key of this mailing lang.
     *
     * @return the primary key of this mailing lang
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this mailing lang.
     *
     * @param primaryKey the primary key of this mailing lang
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the mailing lang ID of this mailing lang.
     *
     * @return the mailing lang ID of this mailing lang
     */
    public long getMailingLangId();

    /**
     * Sets the mailing lang ID of this mailing lang.
     *
     * @param mailingLangId the mailing lang ID of this mailing lang
     */
    public void setMailingLangId(long mailingLangId);

    /**
     * Returns the mailing ID of this mailing lang.
     *
     * @return the mailing ID of this mailing lang
     */
    public long getMailingId();

    /**
     * Sets the mailing ID of this mailing lang.
     *
     * @param mailingId the mailing ID of this mailing lang
     */
    public void setMailingId(long mailingId);

    /**
     * Returns the language ID of this mailing lang.
     *
     * @return the language ID of this mailing lang
     */
    @AutoEscape
    public String getLanguageId();

    /**
     * Sets the language ID of this mailing lang.
     *
     * @param languageId the language ID of this mailing lang
     */
    public void setLanguageId(String languageId);

    /**
     * Returns the email subject pre of this mailing lang.
     *
     * @return the email subject pre of this mailing lang
     */
    @AutoEscape
    public String getEmailSubjectPre();

    /**
     * Sets the email subject pre of this mailing lang.
     *
     * @param emailSubjectPre the email subject pre of this mailing lang
     */
    public void setEmailSubjectPre(String emailSubjectPre);

    /**
     * Returns the email body pre of this mailing lang.
     *
     * @return the email body pre of this mailing lang
     */
    @AutoEscape
    public String getEmailBodyPre();

    /**
     * Sets the email body pre of this mailing lang.
     *
     * @param emailBodyPre the email body pre of this mailing lang
     */
    public void setEmailBodyPre(String emailBodyPre);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(MailingLang mailingLang);

    @Override
    public int hashCode();

    @Override
    public CacheModel<MailingLang> toCacheModel();

    @Override
    public MailingLang toEscapedModel();

    @Override
    public MailingLang toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
