package net.zylk.liferay.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Mailing service. Represents a row in the &quot;ZN_Mailing&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.zylk.liferay.portal.model.impl.MailingModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.zylk.liferay.portal.model.impl.MailingImpl}.
 * </p>
 *
 * @author zylk.net
 * @see Mailing
 * @see net.zylk.liferay.portal.model.impl.MailingImpl
 * @see net.zylk.liferay.portal.model.impl.MailingModelImpl
 * @generated
 */
public interface MailingModel extends BaseModel<Mailing> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a mailing model instance should use the {@link Mailing} interface instead.
     */

    /**
     * Returns the primary key of this mailing.
     *
     * @return the primary key of this mailing
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this mailing.
     *
     * @param primaryKey the primary key of this mailing
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the mailing ID of this mailing.
     *
     * @return the mailing ID of this mailing
     */
    public long getMailingId();

    /**
     * Sets the mailing ID of this mailing.
     *
     * @param mailingId the mailing ID of this mailing
     */
    public void setMailingId(long mailingId);

    /**
     * Returns the company ID of this mailing.
     *
     * @return the company ID of this mailing
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this mailing.
     *
     * @param companyId the company ID of this mailing
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this mailing.
     *
     * @return the group ID of this mailing
     */
    public long getGroupId();

    /**
     * Sets the group ID of this mailing.
     *
     * @param groupId the group ID of this mailing
     */
    public void setGroupId(long groupId);

    /**
     * Returns the newsletter ID of this mailing.
     *
     * @return the newsletter ID of this mailing
     */
    public long getNewsletterId();

    /**
     * Sets the newsletter ID of this mailing.
     *
     * @param newsletterId the newsletter ID of this mailing
     */
    public void setNewsletterId(long newsletterId);

    /**
     * Returns the newsletter name of this mailing.
     *
     * @return the newsletter name of this mailing
     */
    @AutoEscape
    public String getNewsletterName();

    /**
     * Sets the newsletter name of this mailing.
     *
     * @param newsletterName the newsletter name of this mailing
     */
    public void setNewsletterName(String newsletterName);

    /**
     * Returns the email from name of this mailing.
     *
     * @return the email from name of this mailing
     */
    @AutoEscape
    public String getEmailFromName();

    /**
     * Sets the email from name of this mailing.
     *
     * @param emailFromName the email from name of this mailing
     */
    public void setEmailFromName(String emailFromName);

    /**
     * Returns the email from address of this mailing.
     *
     * @return the email from address of this mailing
     */
    @AutoEscape
    public String getEmailFromAddress();

    /**
     * Sets the email from address of this mailing.
     *
     * @param emailFromAddress the email from address of this mailing
     */
    public void setEmailFromAddress(String emailFromAddress);

    /**
     * Returns the start date of this mailing.
     *
     * @return the start date of this mailing
     */
    public Date getStartDate();

    /**
     * Sets the start date of this mailing.
     *
     * @param startDate the start date of this mailing
     */
    public void setStartDate(Date startDate);

    /**
     * Returns the from date of this mailing.
     *
     * @return the from date of this mailing
     */
    public Date getFromDate();

    /**
     * Sets the from date of this mailing.
     *
     * @param fromDate the from date of this mailing
     */
    public void setFromDate(Date fromDate);

    /**
     * Returns the email count of this mailing.
     *
     * @return the email count of this mailing
     */
    public int getEmailCount();

    /**
     * Sets the email count of this mailing.
     *
     * @param emailCount the email count of this mailing
     */
    public void setEmailCount(int emailCount);

    /**
     * Returns the status of this mailing.
     *
     * @return the status of this mailing
     */
    public int getStatus();

    /**
     * Sets the status of this mailing.
     *
     * @param status the status of this mailing
     */
    public void setStatus(int status);

    /**
     * Returns the is scheduled of this mailing.
     *
     * @return the is scheduled of this mailing
     */
    public boolean getIsScheduled();

    /**
     * Returns <code>true</code> if this mailing is is scheduled.
     *
     * @return <code>true</code> if this mailing is is scheduled; <code>false</code> otherwise
     */
    public boolean isIsScheduled();

    /**
     * Sets whether this mailing is is scheduled.
     *
     * @param isScheduled the is scheduled of this mailing
     */
    public void setIsScheduled(boolean isScheduled);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Mailing mailing);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Mailing> toCacheModel();

    @Override
    public Mailing toEscapedModel();

    @Override
    public Mailing toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
