package net.zylk.liferay.portal.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Subscriptor service. Represents a row in the &quot;ZN_Subscriptor&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link net.zylk.liferay.portal.model.impl.SubscriptorModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link net.zylk.liferay.portal.model.impl.SubscriptorImpl}.
 * </p>
 *
 * @author zylk.net
 * @see Subscriptor
 * @see net.zylk.liferay.portal.model.impl.SubscriptorImpl
 * @see net.zylk.liferay.portal.model.impl.SubscriptorModelImpl
 * @generated
 */
public interface SubscriptorModel extends BaseModel<Subscriptor> {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a subscriptor model instance should use the {@link Subscriptor} interface instead.
     */

    /**
     * Returns the primary key of this subscriptor.
     *
     * @return the primary key of this subscriptor
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this subscriptor.
     *
     * @param primaryKey the primary key of this subscriptor
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the uuid of this subscriptor.
     *
     * @return the uuid of this subscriptor
     */
    @AutoEscape
    public String getUuid();

    /**
     * Sets the uuid of this subscriptor.
     *
     * @param uuid the uuid of this subscriptor
     */
    public void setUuid(String uuid);

    /**
     * Returns the subscriptor ID of this subscriptor.
     *
     * @return the subscriptor ID of this subscriptor
     */
    public long getSubscriptorId();

    /**
     * Sets the subscriptor ID of this subscriptor.
     *
     * @param subscriptorId the subscriptor ID of this subscriptor
     */
    public void setSubscriptorId(long subscriptorId);

    /**
     * Returns the company ID of this subscriptor.
     *
     * @return the company ID of this subscriptor
     */
    public long getCompanyId();

    /**
     * Sets the company ID of this subscriptor.
     *
     * @param companyId the company ID of this subscriptor
     */
    public void setCompanyId(long companyId);

    /**
     * Returns the group ID of this subscriptor.
     *
     * @return the group ID of this subscriptor
     */
    public long getGroupId();

    /**
     * Sets the group ID of this subscriptor.
     *
     * @param groupId the group ID of this subscriptor
     */
    public void setGroupId(long groupId);

    /**
     * Returns the name of this subscriptor.
     *
     * @return the name of this subscriptor
     */
    @AutoEscape
    public String getName();

    /**
     * Sets the name of this subscriptor.
     *
     * @param name the name of this subscriptor
     */
    public void setName(String name);

    /**
     * Returns the surname of this subscriptor.
     *
     * @return the surname of this subscriptor
     */
    @AutoEscape
    public String getSurname();

    /**
     * Sets the surname of this subscriptor.
     *
     * @param surname the surname of this subscriptor
     */
    public void setSurname(String surname);

    /**
     * Returns the email of this subscriptor.
     *
     * @return the email of this subscriptor
     */
    @AutoEscape
    public String getEmail();

    /**
     * Sets the email of this subscriptor.
     *
     * @param email the email of this subscriptor
     */
    public void setEmail(String email);

    /**
     * Returns the language ID of this subscriptor.
     *
     * @return the language ID of this subscriptor
     */
    @AutoEscape
    public String getLanguageId();

    /**
     * Sets the language ID of this subscriptor.
     *
     * @param languageId the language ID of this subscriptor
     */
    public void setLanguageId(String languageId);

    /**
     * Returns the self subscribe of this subscriptor.
     *
     * @return the self subscribe of this subscriptor
     */
    public boolean getSelfSubscribe();

    /**
     * Returns <code>true</code> if this subscriptor is self subscribe.
     *
     * @return <code>true</code> if this subscriptor is self subscribe; <code>false</code> otherwise
     */
    public boolean isSelfSubscribe();

    /**
     * Sets whether this subscriptor is self subscribe.
     *
     * @param selfSubscribe the self subscribe of this subscriptor
     */
    public void setSelfSubscribe(boolean selfSubscribe);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Subscriptor subscriptor);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Subscriptor> toCacheModel();

    @Override
    public Subscriptor toEscapedModel();

    @Override
    public Subscriptor toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
